#!/bin/bash
# start.sh — orama-system thin delegator  v0.9.9.8
#
# orama-system is Layer 3 — orchestration / meta-intelligence / delegate runtime.
# All gateway/backend/mode decisions are PT's responsibility (Perpetua-Tools).
# This script: macOS preflight → delegate to PT lifecycle → start orama services.
#
# Starts three services:
#   :8000  Perpetua-Tools orchestrator    (PT — Layer 2)
#   :8001  orama-system reasoning engine  (US)
#   :8002  Portal dashboard
#
# Usage:
#   ./start.sh             — start all, open browser
#   ./start.sh --no-open   — start all, skip browser
#   ./start.sh --stop      — kill all three services
#   ./start.sh --status    — show which ports are listening
#   ./start.sh --discover  — re-run path discovery, rewrite .paths, exit
#
# Path config: .paths (gitignored, auto-generated, user-editable)
# Template:    .paths.example

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PATHS_FILE="$SCRIPT_DIR/.paths"

# ── path resolution: .paths → git siblings → hardcoded sibling default ─────────

_discover_pt_dir() {
  local candidate
  candidate="$(cd "$SCRIPT_DIR/../perplexity-api/Perpetua-Tools" 2>/dev/null && pwd || true)"
  if [ -f "${candidate}/orchestrator/fastapi_app.py" ]; then
    echo "$candidate"; return
  fi
  local root
  root="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "")"
  if [ -n "$root" ]; then
    local parent; parent="$(dirname "$root")"
    for d in "$parent"/*/; do
      if [ -f "${d}orchestrator/fastapi_app.py" ]; then
        cd "$d" && pwd; return
      fi
    done
  fi
  echo "$candidate"
}

_best_python() {
  local dir="$1"
  local venv_py="${dir}/.venv/bin/python"
  if [ -x "$venv_py" ]; then echo "$venv_py"
  else which python3 2>/dev/null || which python
  fi
}

# Load .paths if it exists
PT_DIR=""; PT_PYTHON=""; US_PYTHON=""
if [ -f "$PATHS_FILE" ]; then
  # shellcheck source=/dev/null
  source "$PATHS_FILE"
fi

# Fill in any missing values via discovery
if [ -z "${PT_DIR:-}" ]; then
  PT_DIR="$(_discover_pt_dir)"
fi
if [ -z "${PT_PYTHON:-}" ]; then
  PT_PYTHON="$(_best_python "${PT_DIR:-$SCRIPT_DIR}")"
fi
if [ -z "${US_PYTHON:-}" ]; then
  US_PYTHON="$(_best_python "$SCRIPT_DIR")"
fi

# Write .paths on first run (or if --discover requested)
if [ ! -f "$PATHS_FILE" ] || [[ "${1:-}" == "--discover" ]]; then
  cat > "$PATHS_FILE" << PATHSEOF
# .paths — auto-generated by ./start.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Edit to override. See .paths.example for documentation.
# Regenerate: rm .paths && ./start.sh

PT_DIR="${PT_DIR}"
PT_PYTHON="${PT_PYTHON}"
US_PYTHON="${US_PYTHON}"
PATHSEOF
  echo "  Paths written to .paths (gitignored)"
  [[ "${1:-}" == "--discover" ]] && exit 0
fi

PT_PORT=${PT_PORT:-8000}
US_PORT=${US_PORT:-8001}
PORTAL_PORT=${PORTAL_PORT:-8002}
PORTAL_URL="http://localhost:${PORTAL_PORT}"

LOG_DIR="$SCRIPT_DIR/.logs"
mkdir -p "$LOG_DIR"

# ── macOS pre-flight ──────────────────────────────────────────────────────────
# Applies idempotent fixes to the AlphaClaw binary (macOS compat patches).
# Non-fatal — startup continues on any error.
if [ -f "$SCRIPT_DIR/setup_macos.py" ]; then
  "$US_PYTHON" "$SCRIPT_DIR/setup_macos.py" --quiet 2>&1 | sed 's/^/  /' || true
fi

# ── IP auto-detection ─────────────────────────────────────────────────────────
_IP_VARS="$(cd "$SCRIPT_DIR" && "$US_PYTHON" -c "
import sys, io, contextlib
sys.path.insert(0, '.')
try:
    from network_autoconfig import NetworkAutoConfig
    cfg = NetworkAutoConfig()
    with contextlib.redirect_stdout(io.StringIO()):
        mac_ip = cfg.get_working_local_ip()
    win_ip = cfg.preferred_ips.get('Windows', '192.168.254.103')
    print('MAC_IP=' + mac_ip)
    print('WIN_IP=' + win_ip)
except Exception:
    print('MAC_IP=192.168.254.105')
    print('WIN_IP=192.168.254.103')
" 2>/dev/null)"

eval "$_IP_VARS"
MAC_IP="${MAC_IP:-192.168.254.105}"
WIN_IP="${WIN_IP:-192.168.254.103}"

echo "  IPs   Mac=${MAC_IP}  Win=${WIN_IP}"

# ── PT resolve — backend probe + AlphaClaw bootstrap ─────────────────────────
# Delegates ALL gateway decisions to Perpetua-Tools (Layer 2).
# PT probes backends, determines mode, bootstraps AlphaClaw, and returns
# a JSON payload. orama reads that payload — it makes zero gateway decisions.
#
# PT owns: backend probe (was start.sh §2a), AlphaClaw bootstrap (§2b),
#          mode determination (was §2c).
# See: orchestrator/alphaclaw_manager.py
PT_RESOLVE_OK=0
PT_MODE="offline"
PT_DISTRIBUTED="no"
PT_ALPHACLAW_PORT=""

if [ -n "${PT_DIR:-}" ] && [ -f "${PT_DIR}/orchestrator/alphaclaw_manager.py" ]; then
  echo "  PT    resolving runtime (backends + AlphaClaw)…"
  _PT_ENV_EXPORTS="$(
    MAC_IP="${MAC_IP}" WIN_IP="${WIN_IP}" \
    PYTHONPATH="${PT_DIR}" \
    "$PT_PYTHON" -m orchestrator.alphaclaw_manager \
      --resolve --env-only \
      --mac-ip "${MAC_IP}" --win-ip "${WIN_IP}" \
      2>&1 | tee /dev/stderr | grep '^export '
  )" && PT_RESOLVE_OK=1 || true

  if [ "$PT_RESOLVE_OK" -eq 1 ] && [ -n "$_PT_ENV_EXPORTS" ]; then
    eval "$_PT_ENV_EXPORTS"
    PT_MODE="${PT_MODE:-offline}"
    PT_DISTRIBUTED="${PT_DISTRIBUTED:-no}"
    PT_ALPHACLAW_PORT="${PT_ALPHACLAW_PORT:-}"
    echo "  PT    mode=${PT_MODE}  AlphaClaw=:${PT_ALPHACLAW_PORT}"
    export PT_AGENTS_STATE="${PT_DIR}/.state/routing.json"
  else
    echo "  PT    resolve non-fatal — continuing with defaults"
  fi
else
  # Fallback: PT manager not available — delegate to bootstrap script directly
  PT_HOME="${PT_HOME:-$HOME/Perpetua-Tools}"
  ALPHACLAW_SCRIPT="$PT_HOME/alphaclaw_bootstrap.py"
  if [ -f "$ALPHACLAW_SCRIPT" ]; then
    echo "  AlphaClaw  bootstrapping via PT fallback ($ALPHACLAW_SCRIPT)…"
    PT_HOME="$PT_HOME" UTS_HOME="$SCRIPT_DIR" \
      MAC_IP="${MAC_IP}" WIN_IP="${WIN_IP}" \
      "$US_PYTHON" "$ALPHACLAW_SCRIPT" --bootstrap \
      </dev/null 2>&1 | sed 's/^/  /' \
      || echo "  AlphaClaw  non-fatal — continuing without gateway"
  else
    echo "  PT    not found at ${PT_DIR:-$PT_HOME} — skipping AlphaClaw bootstrap"
  fi
fi

# Export env vars all services read (with user overrides respected)
export OLLAMA_MAC_ENDPOINT="${OLLAMA_MAC_ENDPOINT:-http://${MAC_IP}:11434}"
export OLLAMA_WINDOWS_ENDPOINT="${OLLAMA_WINDOWS_ENDPOINT:-http://${WIN_IP}:11434}"
export LM_STUDIO_MAC_ENDPOINT="${LM_STUDIO_MAC_ENDPOINT:-http://${MAC_IP}:1234}"
export LM_STUDIO_WIN_ENDPOINTS="${LM_STUDIO_WIN_ENDPOINTS:-http://${WIN_IP}:1234}"
export WINDOWS_IP="${WINDOWS_IP:-${WIN_IP}}"
export GPU_BOX="${GPU_BOX:-WINUSER@${WIN_IP}}"

# AlphaClaw security warning — show if running on default password
_AC_PT_HOME="${PT_DIR:-${PT_HOME:-$HOME/Perpetua-Tools}}"
_AC_ONBOARDING="${_AC_PT_HOME}/.state/onboarding.json"
if [ -f "$_AC_ONBOARDING" ]; then
  if "$US_PYTHON" -c "
import json, sys, pathlib
f = pathlib.Path('${_AC_ONBOARDING}')
d = json.loads(f.read_text(encoding='utf-8'))
sys.exit(0 if d.get('alphaclaw', {}).get('password_is_default') else 1)
" 2>/dev/null; then
    echo ""
    echo "  ┌────────────────────────────────────────────────────────────────┐"
    echo "  │  SECURITY  AlphaClaw is running on the DEFAULT password         │"
    echo "  │  Set SETUP_PASSWORD=<yourpassword> in .env and restart          │"
    echo "  └────────────────────────────────────────────────────────────────┘"
    echo ""
  fi
fi

# ── helpers ───────────────────────────────────────────────────────────────────

pid_on_port() { lsof -ti "tcp:$1" 2>/dev/null | head -1 || true; }

wait_for_port() {
  local port=$1 label=$2 tries=0
  printf "  waiting for %s (:%s)" "$label" "$port"
  while ! nc -z localhost "$port" 2>/dev/null; do
    sleep 0.5; tries=$((tries+1))
    printf "."
    if [ $((tries % 60)) -eq 0 ] && [ $tries -gt 0 ]; then
      local elapsed=$((tries / 2))
      local logfile="$LOG_DIR/$(printf '%s' "$label" | tr '[:upper:]' '[:lower:]').log"
      printf "\n  ⚠  %s (:%s) unresponsive for %ds\n" "$label" "$port" "$elapsed"
      if [ -f "$logfile" ]; then
        echo "  last 5 lines of ${logfile}:"
        tail -5 "$logfile" | sed 's/^/    /'
      fi
      printf "  still waiting for %s (:%s)" "$label" "$port"
    fi
    if [ $tries -ge 150 ]; then
      local logfile="$LOG_DIR/$(printf '%s' "$label" | tr '[:upper:]' '[:lower:]').log"
      printf " TIMEOUT — check %s\n" "$logfile"
      return 0  # non-fatal: continue starting remaining services
    fi
  done
  echo " UP"
}

open_browser() {
  local url=$1
  if command -v open &>/dev/null; then open "$url"
  elif command -v xdg-open &>/dev/null; then xdg-open "$url"
  fi
}

# ── --stop ────────────────────────────────────────────────────────────────────

if [[ "${1:-}" == "--stop" ]]; then
  echo "Stopping orama-system services..."
  for port in $PT_PORT $US_PORT $PORTAL_PORT; do
    pid=$(pid_on_port "$port")
    if [ -n "$pid" ]; then
      kill "$pid" 2>/dev/null && echo "  killed PID $pid (:$port)" || true
    else
      echo "  nothing on :$port"
    fi
  done
  exit 0
fi

# ── --status ──────────────────────────────────────────────────────────────────

if [[ "${1:-}" == "--status" ]]; then
  echo ""
  echo "=== orama-system service status ==="
  for port in $PT_PORT $US_PORT $PORTAL_PORT; do
    pid=$(pid_on_port "$port")
    if [ -n "$pid" ]; then
      echo "  UP   :$port  (PID $pid)"
    else
      echo "  DOWN :$port"
    fi
  done
  echo ""
  exit 0
fi

# ── start services ────────────────────────────────────────────────────────────

echo ""
echo "=== orama-system v0.9.9.8 — starting ==="
echo "  Mode: ${PT_MODE}  |  PT → http://localhost:${PT_PORT}"
echo ""

# 1. Perpetua-Tools (PT) orchestrator
if [ -n "$PT_DIR" ] && [ -f "$PT_DIR/orchestrator.py" ]; then
  if pid_on_port "$PT_PORT" | grep -q .; then
    echo "  PT   :$PT_PORT already running"
  else
    echo "  PT   starting → $LOG_DIR/pt.log"
    (cd "$PT_DIR" && PYTHONPATH="$PT_DIR" "$PT_PYTHON" -m uvicorn orchestrator.fastapi_app:app \
      --host 0.0.0.0 --port "$PT_PORT" \
      >> "$LOG_DIR/pt.log" 2>&1) &
    wait_for_port "$PT_PORT" "PT"
  fi
else
  echo "  PT   skipped (not found at ${PT_DIR:-unknown})"
fi

# 2. orama-system reasoning engine
if pid_on_port "$US_PORT" | grep -q .; then
  echo "  orama :$US_PORT already running"
else
  echo "  orama starting → $LOG_DIR/us.log"
  (cd "$SCRIPT_DIR" && PYTHONPATH="$SCRIPT_DIR" "$US_PYTHON" -m uvicorn api_server:app \
    --host 0.0.0.0 --port "$US_PORT" \
    >> "$LOG_DIR/us.log" 2>&1) &
  wait_for_port "$US_PORT" "orama"
fi

# 3. Portal
if pid_on_port "$PORTAL_PORT" | grep -q .; then
  echo "  Portal :$PORTAL_PORT already running"
else
  echo "  Portal starting → $LOG_DIR/portal.log"
  (cd "$SCRIPT_DIR" && PYTHONPATH="$SCRIPT_DIR" "$US_PYTHON" -m uvicorn portal_server:app \
    --host 0.0.0.0 --port "$PORTAL_PORT" \
    >> "$LOG_DIR/portal.log" 2>&1) &
  wait_for_port "$PORTAL_PORT" "Portal"
fi

echo ""
echo "  PT     http://localhost:${PT_PORT}/health"
echo "  orama  http://localhost:${US_PORT}/health"
echo "  Portal ${PORTAL_URL}"
echo "  JSON   ${PORTAL_URL}/api/status"
echo ""

if [[ "${1:-}" != "--no-open" ]]; then
  open_browser "$PORTAL_URL"
fi

echo "Logs: $LOG_DIR/"
echo "Stop: ./start.sh --stop"
echo ""
