#!/bin/bash
# start.sh — ultrathink v1.0 RC first-run launcher
#
# Starts three services in background, then opens the portal in your browser:
#   :8000  Perplexity-Tools orchestrator  (PT)
#   :8001  ultrathink reasoning engine    (US)
#   :8002  Portal dashboard               (this file)
#
# Usage:
#   ./start.sh             — start all, open browser (writes .paths on first run)
#   ./start.sh --no-open   — start all, skip browser open
#   ./start.sh --stop      — kill all three services
#   ./start.sh --status    — show which ports are listening
#   ./start.sh --discover  — re-run path discovery, rewrite .paths, exit
#
# Path config: .paths (gitignored, auto-generated, user-editable)
# Template:    .paths.example

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PATHS_FILE="$SCRIPT_DIR/.paths"

# ── path resolution: .paths file → git discovery → hardcoded sibling default ──
#
# Priority (per variable):
#   1. Value in .paths (gitignored, machine-local, user-editable)
#   2. Auto-discovered: git worktree siblings, then hardcoded sibling path
#   3. Written back to .paths on first discovery so future runs are instant
#
# To reconfigure: rm .paths && ./start.sh  OR  edit .paths directly
# Template:       .paths.example

_discover_pt_dir() {
  # 1. Try known sibling path (matches this repo's git layout)
  local candidate
  candidate="$(cd "$SCRIPT_DIR/../perplexity-api/Perplexity-Tools" 2>/dev/null && pwd || true)"
  if [ -f "${candidate}/orchestrator/fastapi_app.py" ]; then
    echo "$candidate"; return
  fi
  # 2. Walk git worktree siblings looking for Perplexity-Tools
  local root
  root="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || echo "")"
  if [ -n "$root" ]; then
    local parent; parent="$(dirname "$root")"
    for d in "$parent"/*/; do
      if [ -f "${d}orchestrator/fastapi_app.py" ]; then
        cd "$d" && pwd; return
      fi
    done
  fi
  echo ""
}

_best_python() {
  local dir="$1"
  local venv_py="${dir}/.venv/bin/python"
  if [ -x "$venv_py" ]; then echo "$venv_py"
  else which python3 2>/dev/null || which python
  fi
}

# Load .paths if it exists
PT_DIR=""; PT_PYTHON=""; US_PYTHON=""
if [ -f "$PATHS_FILE" ]; then
  # shellcheck source=/dev/null
  source "$PATHS_FILE"
fi

# Fill in any missing values via discovery
if [ -z "${PT_DIR:-}" ]; then
  PT_DIR="$(_discover_pt_dir)"
fi
if [ -z "${PT_PYTHON:-}" ]; then
  PT_PYTHON="$(_best_python "${PT_DIR:-$SCRIPT_DIR}")"
fi
if [ -z "${US_PYTHON:-}" ]; then
  US_PYTHON="$(_best_python "$SCRIPT_DIR")"
fi

# Write .paths on first run (or if --discover requested)
if [ ! -f "$PATHS_FILE" ] || [[ "${1:-}" == "--discover" ]]; then
  cat > "$PATHS_FILE" << PATHSEOF
# .paths — auto-generated by ./start.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Edit to override. See .paths.example for documentation.
# Regenerate: rm .paths && ./start.sh

PT_DIR="${PT_DIR}"
PT_PYTHON="${PT_PYTHON}"
US_PYTHON="${US_PYTHON}"
PATHSEOF
  echo "  Paths written to .paths (gitignored)"
  [[ "${1:-}" == "--discover" ]] && exit 0
fi

PT_PORT=${PT_PORT:-8000}
US_PORT=${US_PORT:-8001}
PORTAL_PORT=${PORTAL_PORT:-8002}
PORTAL_URL="http://localhost:${PORTAL_PORT}"

LOG_DIR="$SCRIPT_DIR/.logs"
mkdir -p "$LOG_DIR"

# ── helpers ───────────────────────────────────────────────────────────────────

pid_on_port() { lsof -ti "tcp:$1" 2>/dev/null | head -1 || true; }

wait_for_port() {
  local port=$1 label=$2 tries=0
  printf "  waiting for %s (:%s)" "$label" "$port"
  while ! nc -z localhost "$port" 2>/dev/null; do
    sleep 0.5; tries=$((tries+1))
    printf "."
    if [ $tries -ge 40 ]; then echo " TIMEOUT"; return 1; fi
  done
  echo " UP"
}

open_browser() {
  local url=$1
  if command -v open &>/dev/null; then open "$url"          # macOS
  elif command -v xdg-open &>/dev/null; then xdg-open "$url" # Linux
  fi
}

# ── --stop ────────────────────────────────────────────────────────────────────

if [[ "${1:-}" == "--stop" ]]; then
  echo "Stopping ultrathink services..."
  for port in $PT_PORT $US_PORT $PORTAL_PORT; do
    pid=$(pid_on_port "$port")
    if [ -n "$pid" ]; then
      kill "$pid" 2>/dev/null && echo "  killed PID $pid (:$port)" || true
    else
      echo "  nothing on :$port"
    fi
  done
  exit 0
fi

# ── --status ──────────────────────────────────────────────────────────────────

if [[ "${1:-}" == "--status" ]]; then
  echo ""
  echo "=== ultrathink service status ==="
  for port in $PT_PORT $US_PORT $PORTAL_PORT; do
    pid=$(pid_on_port "$port")
    if [ -n "$pid" ]; then
      echo "  UP   :$port  (PID $pid)"
    else
      echo "  DOWN :$port"
    fi
  done
  echo ""
  exit 0
fi

# ── start ─────────────────────────────────────────────────────────────────────

echo ""
echo "=== ultrathink v1.0 RC — starting ==="
echo ""

# 1. Perplexity-Tools (PT)
if [ -n "$PT_DIR" ] && [ -f "$PT_DIR/orchestrator.py" ]; then
  if pid_on_port "$PT_PORT" | grep -q .; then
    echo "  PT   :$PT_PORT already running"
  else
    echo "  PT   starting → $LOG_DIR/pt.log"
    (cd "$PT_DIR" && PYTHONPATH="$PT_DIR" "$PT_PYTHON" -m uvicorn orchestrator.fastapi_app:app \
      --host 0.0.0.0 --port "$PT_PORT" \
      >> "$LOG_DIR/pt.log" 2>&1) &
    wait_for_port "$PT_PORT" "PT"
  fi
else
  echo "  PT   skipped (not found at $PT_DIR)"
fi

# 2. ultrathink api_server (US)
if pid_on_port "$US_PORT" | grep -q .; then
  echo "  US   :$US_PORT already running"
else
  echo "  US   starting → $LOG_DIR/us.log"
  (cd "$SCRIPT_DIR" && PYTHONPATH="$SCRIPT_DIR" "$US_PYTHON" -m uvicorn api_server:app \
    --host 0.0.0.0 --port "$US_PORT" \
    >> "$LOG_DIR/us.log" 2>&1) &
  wait_for_port "$US_PORT" "US"
fi

# 3. Portal
if pid_on_port "$PORTAL_PORT" | grep -q .; then
  echo "  Portal :$PORTAL_PORT already running"
else
  echo "  Portal starting → $LOG_DIR/portal.log"
  (cd "$SCRIPT_DIR" && PYTHONPATH="$SCRIPT_DIR" "$US_PYTHON" -m uvicorn portal_server:app \
    --host 0.0.0.0 --port "$PORTAL_PORT" \
    >> "$LOG_DIR/portal.log" 2>&1) &
  wait_for_port "$PORTAL_PORT" "Portal"
fi

echo ""
echo "  PT     http://localhost:${PT_PORT}/health"
echo "  US     http://localhost:${US_PORT}/health"
echo "  Portal ${PORTAL_URL}"
echo "  JSON   ${PORTAL_URL}/api/status"
echo ""

# Open browser unless suppressed
if [[ "${1:-}" != "--no-open" ]]; then
  open_browser "$PORTAL_URL"
fi

echo "Logs: $LOG_DIR/"
echo "Stop: ./start.sh --stop"
echo ""
