#!/usr/bin/env bash
# install_network_watch.sh — install/uninstall the orama network-change watcher
# Usage:
#   ./scripts/install_network_watch.sh           # install (idempotent)
#   ./scripts/install_network_watch.sh --uninstall
#   ./scripts/install_network_watch.sh --status

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(dirname "$SCRIPT_DIR")"
DISCOVER_PY="$SCRIPT_DIR/discover.py"
PLIST_TEMPLATE="$REPO_DIR/config/com.orama.network-watch.plist"
LAUNCH_AGENTS="$HOME/Library/LaunchAgents"
PLIST_DEST="$LAUNCH_AGENTS/com.orama.network-watch.plist"
LABEL="com.orama.network-watch"

# Resolve Perpetua-Tools root (best effort)
PT_ROOT="${PERPETUA_TOOLS_ROOT:-${PERPETUATOOLSROOT:-}}"
if [ -z "$PT_ROOT" ]; then
    PT_CANDIDATE="$HOME/Documents/Terminal xCode/claude/OpenClaw/perplexity-api/Perpetua-Tools"
    [ -d "$PT_CANDIDATE" ] && PT_ROOT="$PT_CANDIDATE"
fi

_status() {
    if launchctl list | grep -q "$LABEL" 2>/dev/null; then
        echo "✅ $LABEL is loaded"
        launchctl list "$LABEL" 2>/dev/null | grep -E "PID|LastExitStatus" || true
    else
        echo "❌ $LABEL is NOT loaded"
    fi
    if [ -f "$HOME/.openclaw/state/network-watch.log" ]; then
        echo "--- last 5 log lines ---"
        tail -5 "$HOME/.openclaw/state/network-watch.log"
    fi
}

_uninstall() {
    echo "Uninstalling $LABEL..."
    launchctl unload "$PLIST_DEST" 2>/dev/null || true
    rm -f "$PLIST_DEST"
    echo "✅ Uninstalled."
}

_install() {
    echo "Installing orama network-change watcher..."
    mkdir -p "$LAUNCH_AGENTS"
    mkdir -p "$HOME/.openclaw/state"

    # Resolve python3 that has Full Disk Access (prefer homebrew/user-installed over
    # CommandLineTools which is sandboxed by TCC in launchd context)
    PYTHON3=""
    for candidate in \
        /opt/homebrew/bin/python3.13 \
        /opt/homebrew/bin/python3 \
        /usr/local/bin/python3 \
        /usr/bin/python3; do
        if "$candidate" -c "import sys; sys.exit(0)" 2>/dev/null; then
            PYTHON3="$candidate"
            break
        fi
    done
    if [ -z "$PYTHON3" ]; then echo "❌ No python3 found"; exit 1; fi
    echo "  Using python3: $PYTHON3"

    # Write a wrapper shell script — launchd runs this, which inherits the correct
    # python3 with TCC-granted permissions (avoids CommandLineTools sandbox issue)
    WRAPPER="$HOME/.openclaw/state/network-watch-run.sh"
    cat > "$WRAPPER" << WRAPPER_EOF
#!/bin/bash
# Auto-generated by install_network_watch.sh — do not edit
export PERPETUA_TOOLS_ROOT="${PT_ROOT}"
exec "${PYTHON3}" "${DISCOVER_PY}" --watch --watch-interval 30
WRAPPER_EOF
    chmod +x "$WRAPPER"

    # Write plist pointing at the wrapper (not discover.py directly)
    cat > "$PLIST_DEST" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.orama.network-watch</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>${WRAPPER}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>ThrottleInterval</key>
    <integer>60</integer>
    <key>StandardOutPath</key>
    <string>${HOME}/.openclaw/state/network-watch.log</string>
    <key>StandardErrorPath</key>
    <string>${HOME}/.openclaw/state/network-watch.log</string>
</dict>
</plist>
PLIST_EOF

    # Unload old version first (idempotent)
    launchctl unload "$PLIST_DEST" 2>/dev/null || true
    launchctl load "$PLIST_DEST"

    echo "✅ Installed and started: $LABEL"
    echo "   Wrapper: $WRAPPER"
    echo "   Log: $HOME/.openclaw/state/network-watch.log"
    echo "   Uninstall: ./scripts/install_network_watch.sh --uninstall"
    _status
}

case "${1:-}" in
    --uninstall) _uninstall ;;
    --status)    _status ;;
    *)           _install ;;
esac
